name: MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install dvc[s3]

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1
        
    - name: Pull Data and Models
      run: dvc pull

    - name: Run DVC Pipeline
      run: dvc repro

    - name: Push Results to DVC Remote
      run: dvc push

    - name: Commit and Push Changes
      run: |
        git config --global user.name "neeraj singh"
        git config --global user.email "neeraj@gmail.com"
        git add .
        git commit -m "Update pipeline artifacts"
        git push
