name: MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install dvc[s3]

    - name: Pull Data and Models
      run: dvc pull

    - name: Run DVC Pipeline
      run: dvc repro

    - name: Push Results to DVC Remote
      run: dvc push

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Update pipeline artifacts"
        git push
